/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tra_metodos;

import javax.swing.table.DefaultTableModel;
import tra_metodos.funcoes.Calculo_Segundo_Grau;
import tra_metodos.funcoes.Integral;
import tra_metodos.funcoes.Ponto_Final_ExA;
import tra_metodos.funcoes.Ponto_Final_ExB;

/**
 *
 * @author Fabricio Junior
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Intervalo_A = new java.awt.TextField();
        Intervalo_B = new java.awt.TextField();
        N_Retangulos_Text = new java.awt.TextField();
        Constante_A_Texto = new java.awt.TextField();
        Constante_B_Text = new java.awt.TextField();
        Constante_C_Text = new java.awt.TextField();
        Equacao_LinearButton = new javax.swing.JRadioButton();
        Start_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fuction = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Resultado_PontoMedio = new java.awt.TextField();
        Resultado_RetanguloEsquerda = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel10 = new javax.swing.JLabel();
        Resultado_RetanguloDireita = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Principal_Resultado_PontoMedioComposto = new java.awt.TextField();
        Resultado_ValorReal = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        RetânguloComposto = new javax.swing.JLabel();
        Resultado_RetanguloComposto = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Resultado_RetanguloCompostoDireito = new java.awt.TextField();
        Resultado_RetanguloCompostoEsquerdo = new java.awt.TextField();
        exB = new javax.swing.JButton();
        cos_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Intervalo_A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Intervalo_AFocusLost(evt);
            }
        });
        getContentPane().add(Intervalo_A);
        Intervalo_A.setBounds(29, 127, 82, 20);
        getContentPane().add(Intervalo_B);
        Intervalo_B.setBounds(29, 160, 82, 20);

        N_Retangulos_Text.setText("4");
        getContentPane().add(N_Retangulos_Text);
        N_Retangulos_Text.setBounds(29, 219, 82, 20);
        getContentPane().add(Constante_A_Texto);
        Constante_A_Texto.setBounds(30, 280, 162, 20);
        getContentPane().add(Constante_B_Text);
        Constante_B_Text.setBounds(30, 300, 162, 20);
        getContentPane().add(Constante_C_Text);
        Constante_C_Text.setBounds(30, 320, 162, 20);

        Equacao_LinearButton.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        Equacao_LinearButton.setText("Equação Linear");
        Equacao_LinearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Equacao_LinearButtonMouseClicked(evt);
            }
        });
        getContentPane().add(Equacao_LinearButton);
        Equacao_LinearButton.setBounds(0, 350, 111, 27);

        Start_Button.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Start_Button.setText("Start");
        Start_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartButton(evt);
            }
        });
        Start_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Start_Button);
        Start_Button.setBounds(10, 390, 102, 48);
        Start_Button.getAccessibleContext().setAccessibleName("Start_Button");

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setText("Ponto Medio:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(302, 222, 93, 23);

        jLabel2.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jLabel2.setText("a:");
        jLabel2.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 280, 19, 18);

        jLabel3.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jLabel3.setText("b:");
        jLabel3.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 300, 19, 18);

        jLabel4.setFont(new java.awt.Font("Impact", 2, 14)); // NOI18N
        jLabel4.setText("c:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 320, 19, 18);

        fuction.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        fuction.setText("f(x) = aX²+bX+c");
        fuction.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fuction);
        fuction.setBounds(0, 52, 193, 28);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel5.setText("MÉTODOS DO RETÂNGULO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 351, 45);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel6.setText("Resultados:");
        jLabel6.setToolTipText("");
        jLabel6.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(283, 51, 114, 31);
        getContentPane().add(Resultado_PontoMedio);
        Resultado_PontoMedio.setBounds(400, 227, 82, 20);
        getContentPane().add(Resultado_RetanguloEsquerda);
        Resultado_RetanguloEsquerda.setBounds(400, 138, 82, 20);

        jLabel7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel7.setText("A:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 124, 19, 23);

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setText("Retângulo(Esquerda):");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 133, 156, 23);

        jLabel9.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel9.setText("B:");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 157, 19, 23);

        label1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        label1.setText("Constantes:");
        getContentPane().add(label1);
        label1.setBounds(0, 250, 72, 22);
        label1.getAccessibleContext().setAccessibleDescription("");

        label2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        label2.setText("Intervalo[A,B]:");
        getContentPane().add(label2);
        label2.setBounds(0, 92, 84, 22);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel10.setText("Retângulo(Direita):");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(257, 157, 139, 23);
        getContentPane().add(Resultado_RetanguloDireita);
        Resultado_RetanguloDireita.setBounds(400, 160, 82, 20);

        jLabel11.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel11.setText("Número de retângulos(n):");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 191, 142, 18);

        jLabel12.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel12.setText("n:");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 216, 19, 23);

        jLabel13.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel13.setText("Ponto Medio Composto:");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 248, 168, 23);
        getContentPane().add(Principal_Resultado_PontoMedioComposto);
        Principal_Resultado_PontoMedioComposto.setBounds(400, 250, 82, 20);
        getContentPane().add(Resultado_ValorReal);
        Resultado_ValorReal.setBounds(400, 95, 82, 20);

        jLabel14.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel14.setText("Valor Real:");
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(317, 92, 78, 23);

        RetânguloComposto.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        RetânguloComposto.setText("Retângulo Composto:");
        RetânguloComposto.setToolTipText("");
        getContentPane().add(RetânguloComposto);
        RetânguloComposto.setBounds(240, 110, 160, 23);
        getContentPane().add(Resultado_RetanguloComposto);
        Resultado_RetanguloComposto.setBounds(400, 116, 82, 20);

        jLabel15.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel15.setText("Retângulo Composto(Esquerdo):");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(166, 180, 231, 23);

        jLabel16.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel16.setText("Retângulo Composto(Direito):");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(182, 202, 214, 20);
        getContentPane().add(Resultado_RetanguloCompostoDireito);
        Resultado_RetanguloCompostoDireito.setBounds(400, 200, 82, 20);
        getContentPane().add(Resultado_RetanguloCompostoEsquerdo);
        Resultado_RetanguloCompostoEsquerdo.setBounds(400, 180, 82, 20);

        exB.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        exB.setText("x¹/²  + 1");
        exB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exBStartButton(evt);
            }
        });
        exB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBActionPerformed(evt);
            }
        });
        getContentPane().add(exB);
        exB.setBounds(250, 390, 102, 48);
        exB.getAccessibleContext().setAccessibleName("x¹/²  + 1");

        cos_button.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        cos_button.setLabel("cos(x)");
        cos_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cos_buttonStartButton(evt);
            }
        });
        cos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cos_button);
        cos_button.setBounds(130, 390, 102, 48);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Equacao_LinearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Equacao_LinearButtonMouseClicked
        // TODO add your handling code here:
        if (Equacao_LinearButton.isSelected()) {
            fuction.setText("f(x)= aX+B");
            Constante_C_Text.setEnabled(false);
        } else {
            fuction.setText("f(x) = aX²+bX+c");
            Constante_C_Text.setEnabled(true);
        }
    }//GEN-LAST:event_Equacao_LinearButtonMouseClicked

    private void StartButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartButton

        Calculo calculo;
        if (Equacao_LinearButton.isSelected()) {
            calculo = new Integral();
            String constanteA = Constante_A_Texto.getText();
            String constanteB = Constante_B_Text.getText();
            calculo.setConstantes(Double.valueOf(constanteA), Double.valueOf(constanteB), 00);

        } else {
            calculo = new Calculo_Segundo_Grau();
            String constanteA = Constante_A_Texto.getText();
            String constanteB = Constante_B_Text.getText();
            String constanteC = Constante_C_Text.getText();
            calculo.setConstantes(Double.valueOf(constanteA), Double.valueOf(constanteB), Double.valueOf(constanteC));
        }
        String intervaloA = Intervalo_A.getText();
        String intervaloB = Intervalo_B.getText();
        calculo.setIntervalo(Double.valueOf(intervaloA), Double.valueOf(intervaloB));
        calculo.setRetangulos(Integer.parseInt(N_Retangulos_Text.getText()));
        Resultado_PontoMedio.setText(String.valueOf(calculo.getResultadoPontoCentral()));
        Resultado_RetanguloDireita.setText(String.valueOf(calculo.getResultadoRetangulo_Direita()));
        Resultado_RetanguloEsquerda.setText(String.valueOf(calculo.getResultadoRetangulo_Esquerda()));
        Principal_Resultado_PontoMedioComposto.setText(String.valueOf(calculo.getResultadoPontoCentralComposto()));
        Resultado_ValorReal.setText(String.valueOf(calculo.getResultadoReal()));
        Resultado_RetanguloComposto.setText(String.valueOf(calculo.getResultadoRetanguloComposto()));
        Resultado_RetanguloCompostoDireito.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Direita()));
        Resultado_RetanguloCompostoEsquerdo.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Esquerda()));
    }//GEN-LAST:event_StartButton

    private void Start_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_ButtonActionPerformed

    private void Intervalo_AFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Intervalo_AFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Intervalo_AFocusLost

    private void exBStartButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exBStartButton
        Calculo calculo = new Ponto_Final_ExA();
        String intervaloA = Intervalo_A.getText();
        String intervaloB = Intervalo_B.getText();
        calculo.setIntervalo(Double.valueOf(intervaloA), Double.valueOf(intervaloB));
        calculo.setRetangulos(Integer.parseInt(N_Retangulos_Text.getText()));
        Resultado_PontoMedio.setText(String.valueOf(calculo.getResultadoPontoCentral()));
        Resultado_RetanguloDireita.setText(String.valueOf(calculo.getResultadoRetangulo_Direita()));
        Resultado_RetanguloEsquerda.setText(String.valueOf(calculo.getResultadoRetangulo_Esquerda()));
        Principal_Resultado_PontoMedioComposto.setText(String.valueOf(calculo.getResultadoPontoCentralComposto()));
        Resultado_ValorReal.setText(String.valueOf(calculo.getResultadoReal()));
        Resultado_RetanguloComposto.setText(String.valueOf(calculo.getResultadoRetanguloComposto()));
        Resultado_RetanguloCompostoDireito.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Direita()));
        Resultado_RetanguloCompostoEsquerdo.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Esquerda()));
    }//GEN-LAST:event_exBStartButton

    private void exBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exBActionPerformed

    private void cos_buttonStartButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cos_buttonStartButton
        Calculo calculo = new Ponto_Final_ExB();
        String intervaloA = Intervalo_A.getText();
        String intervaloB = Intervalo_B.getText();
        calculo.setIntervalo(Double.valueOf(intervaloA), Double.valueOf(intervaloB));
        calculo.setRetangulos(Integer.parseInt(N_Retangulos_Text.getText()));
        Resultado_PontoMedio.setText(String.valueOf(calculo.getResultadoPontoCentral()));
        Resultado_RetanguloDireita.setText(String.valueOf(calculo.getResultadoRetangulo_Direita()));
        Resultado_RetanguloEsquerda.setText(String.valueOf(calculo.getResultadoRetangulo_Esquerda()));
        Principal_Resultado_PontoMedioComposto.setText(String.valueOf(calculo.getResultadoPontoCentralComposto()));
        Resultado_ValorReal.setText(String.valueOf(calculo.getResultadoReal()));
        Resultado_RetanguloComposto.setText(String.valueOf(calculo.getResultadoRetanguloComposto()));
        Resultado_RetanguloCompostoDireito.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Direita()));
        Resultado_RetanguloCompostoEsquerdo.setText(String.valueOf(calculo.getResultadoRetanguloComposto_Esquerda()));
    }//GEN-LAST:event_cos_buttonStartButton

    private void cos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cos_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Constante_A_Texto;
    private java.awt.TextField Constante_B_Text;
    private java.awt.TextField Constante_C_Text;
    private javax.swing.JRadioButton Equacao_LinearButton;
    private java.awt.TextField Intervalo_A;
    private java.awt.TextField Intervalo_B;
    private java.awt.TextField N_Retangulos_Text;
    private java.awt.TextField Principal_Resultado_PontoMedioComposto;
    private java.awt.TextField Resultado_PontoMedio;
    private java.awt.TextField Resultado_RetanguloComposto;
    private java.awt.TextField Resultado_RetanguloCompostoDireito;
    private java.awt.TextField Resultado_RetanguloCompostoEsquerdo;
    private java.awt.TextField Resultado_RetanguloDireita;
    private java.awt.TextField Resultado_RetanguloEsquerda;
    private java.awt.TextField Resultado_ValorReal;
    private javax.swing.JLabel RetânguloComposto;
    private javax.swing.JButton Start_Button;
    private javax.swing.JButton cos_button;
    private javax.swing.JButton exB;
    private javax.swing.JLabel fuction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
